# Numpy- Numerical Python
- NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of     routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.
- deals with numerical data
- contains n-dimensional arrays

# Numpy
Numpy : Numerical python

### Advantages:

convenience and speed
Numpy is much faster than the standard python ways to do computations
Can write vectorised code on numpy arrays, not on lists
which is convenient to read and write
It takes Less memory as compared to python lists
Can handle the vast amount of data
a. Used for scientific computing and data analysis b. Written as ndarray (n-dimensional , homogeneous) or array

Commonly integers or floats c. Creating Numpy Arrays:
1D, 2D, 3D array
Convert lists, tuple to np.arrays
d. Initialize Array:

np.ones(shape,dtype)
np.zeros(shape,dtype)
np.random.random(shape)
np.arange(start,end,step)
np.linspace(start,end,length of array)
np.full(shape,value)
np.tile(array,number of repetitions) or (array,shape)
np.eye(value,dtype) - identical matrix
np.random.randint(start,end,shape)
np.nonzero(array)
max,min,median,mode
array Transpose
np.vstack(array)
np.hstack(array
argsort,argmin,argmax,np.log10,pi
e. Inspect the structure and content of array

np.shape(array)
np.dtype()
np.ndim()
np.itemsize()
np.reshape(factors of size of array)

#### Python Libraries for Data Science
- Numpy
- Pandas
- Matplotlib

In [1]:
import numpy as np

In [2]:
! pip install numpy

In [6]:
numpy.array([1,2,3])


NameError: name 'numpy' is not defined

In [5]:
np.array([1,2,3])


array([1, 2, 3])

In [8]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [9]:
a = np.array([1,2,3,7])
print(a)
a

[1 2 3 7]


array([1, 2, 3, 7])

In [6]:
l=[9,6,7,5,3]
b=np.array(l)
#type(b)
b

array([9, 6, 7, 5, 3])

In [8]:
# create 1D array
array_1d = np.array([2,4,5,6,7,8])
print(array_1d)

[2 4 5 6 7 8]


In [7]:
# create 2D array
array_2d = np.array([[2,4,5],[6,7,8]])
print(array_2d)

[[2 4 5]
 [6 7 8]]


### Numpy Properties
- ndim
     - no of dimensions of the array
- shape
     - returns the length of an array
- dtype
     - datatype of an element in an array
- size
     - returns the size of the array
- itemsize
     - returns the size of an element in bytes

In [17]:
# using ndim,shape,dtype,size,itemsize
a1 = np.array([2,4,6,8,10,"z"])
print(a1.ndim)
print(a1.shape)
print(a1.size)       
print(a1.itemsize)
print(a1.dtype)    #<u unicode format


1
(6,)
6
44
<U11


In [20]:
a1 = np.array([2,4,6,8,10])
print(a1.ndim)
print(a1.shape)
print(a1.size)
print(a1.itemsize)
print(a1.dtype)


1
(5,)
5
4
int32


In [21]:
a1 = np.array([2,4,6,8,10,"z"])
print(a1.ndim)
print(a1.shape)
print(a1.size)
print(a1.itemsize)
print(a1.dtype)
a1


1
(6,)
6
44
<U11


array(['2', '4', '6', '8', '10', 'z'], dtype='<U11')

In [23]:
#2d array
a2 = np.array([[1,2,3], [4,5,6]])
print(a2.ndim)
print(a2)

2
[[1 2 3]
 [4 5 6]]


In [26]:
#printing 1D array using arange
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
#taking step as 3
a = np.arange(1,15,3)
a

array([ 1,  4,  7, 10, 13])

In [29]:
a = np.arange(2,15,3)
a

array([ 2,  5,  8, 11, 14])

In [8]:
# for directly displaying in multi dimension we use reshape
sa=np.arange(15).reshape(3,5)
sa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
#reverse the array
sa[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [50]:
r = np.random.randint(1,50,size=(3,3,3,3))
r

array([[[[40, 16, 32],
         [34, 15,  5],
         [37, 21, 11]],

        [[ 6, 23, 18],
         [29, 16,  8],
         [12, 19, 48]],

        [[20, 26, 45],
         [21,  9,  2],
         [24, 10, 27]]],


       [[[36, 23, 39],
         [35, 43, 33],
         [22,  3, 31]],

        [[ 8,  8, 21],
         [13, 36, 26],
         [49, 15, 23]],

        [[15,  7, 38],
         [46, 11, 35],
         [43, 19, 11]]],


       [[[35, 22, 46],
         [31, 10, 41],
         [31, 48, 14]],

        [[23, 46, 35],
         [23, 35, 19],
         [ 3, 12, 23]],

        [[41, 37, 48],
         [23, 49,  2],
         [33, 43, 21]]]])

In [51]:
r = np.random.randint(1,50,size=(3,3,3,2))
r

array([[[[46, 23],
         [45, 20],
         [ 7, 29]],

        [[39,  8],
         [27, 19],
         [22, 40]],

        [[12, 36],
         [39, 20],
         [11, 10]]],


       [[[10, 21],
         [ 4, 27],
         [ 7,  3]],

        [[38, 15],
         [36, 48],
         [ 5,  9]],

        [[45,  3],
         [11, 22],
         [16, 17]]],


       [[[38,  4],
         [49,  9],
         [36,  4]],

        [[15, 12],
         [30, 48],
         [12, 10]],

        [[ 8, 28],
         [46, 39],
         [32, 29]]]])

In [10]:
sa

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
ad = sa+1

In [12]:
ad

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [60]:
a=np.array([1,2,46,7,8,9])
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.exp(a))
print(np.log(a))


[1.         1.41421356 6.78232998 2.64575131 2.82842712 3.        ]
[0.84147098 0.90929743 0.90178835 0.6569866  0.98935825 0.41211849]
[ 0.54030231 -0.41614684 -0.43217794  0.75390225 -0.14550003 -0.91113026]
[2.71828183e+00 7.38905610e+00 9.49611942e+19 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[0.         0.69314718 3.8286414  1.94591015 2.07944154 2.19722458]


In [16]:
o=np.ones((3,3))
z=np.zeros((3,3))
print(o)
z

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
k=np.linspace(0,2,5) #creates an array evenly
k                    

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
f=np.full((2,2),7)  # creates a constant array (2,2) is size of matrix 7 is elment to enter in it
f

array([[7, 7],
       [7, 7]])

In [28]:
arr8 = np.nonzero([1,2,0,5,0,7,5]) # it returns nonzero elements indices
arr8

(array([0, 1, 3, 5, 6], dtype=int64),)

In [30]:
e=np.eye(2) # creates a 2*2 array identity matrix
e

array([[1., 0.],
       [0., 1.]])

In [18]:
r=np.random.random((2,2)) # creates arrays with random values
r

array([[0.28311235, 0.6660501 ],
       [0.72348933, 0.00080398]])

In [19]:
em=np.empty((3,2))
em

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
s=np.array([1,2,3,5,6])
s[-1]

6

In [23]:
s=np.array([1,2,3,5,6])
s[1]

2

In [20]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a[0]

array([1, 2, 3])

In [22]:
a[1]

array([4, 5, 6])

In [24]:
#2D array slicing
a[0][1]  # to access elem from 1,2,3 

2

In [25]:
a[1][2] # to access elements from 4,5,6

6

In [27]:
a[0:2,1]

array([2, 5])

In [28]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a[0:1]

array([[1, 2, 3]])

In [25]:
a[0:1,2]

array([3])

In [31]:
a[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

In [32]:
a[a<3]

array([1, 2])

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a[[1,0,1,0],[0,1,2,0]] #(1,0),(0,1),(1,2),(0,0)
                       # (1,0)-->1st index 0th element

array([4, 2, 6, 1])

In [35]:
a1=np.array([[1,4,5],[2,3,5]])
print(np.add(a,a1))
print(np.subtract(a,a1))
print(np.multiply(a,a1))
print(np.divide(a,a1))

[[ 2  6  8]
 [ 6  8 11]]
[[ 0 -2 -2]
 [ 2  2  1]]
[[ 1  8 15]
 [ 8 15 30]]
[[1.         0.5        0.6       ]
 [2.         1.66666667 1.2       ]]


In [38]:
e.dot(f) # e is identity matrix and f is full matrix

array([[7., 7.],
       [7., 7.]])

In [39]:
np.info(np.ndarray.ndim) #dim -dimension

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3


In [40]:
np.info(np.ndarray.size) #dim -dimension

Number of elements in the array.

Equal to ``np.prod(a.shape)``, i.e., the product of the array's
dimensions.

Notes
-----
`a.size` returns a standard arbitrary precision Python integer. This
may not be the case with other methods of obtaining the same value
(like the suggested ``np.prod(a.shape)``, which returns an instance
of ``np.int_``), and may be relevant if the value is used further in
calculations that may overflow a fixed size integer type.

Examples
--------
>>> x = np.zeros((3, 5, 2), dtype=np.complex128)
>>> x.size
30
>>> np.prod(x.shape)
30


In [43]:
a1.dtype

dtype('int32')

In [47]:
# to convert to float 
a1.astype(float)

array([[1., 4., 5.],
       [2., 3., 5.]])

In [45]:
h=a1.view()

In [46]:
h

array([[1, 4, 5],
       [2, 3, 5]])

In [31]:
t=np.save('my_array',a)
t

In [32]:
t1=np.load('my_array.npy')

In [33]:
t1

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a.sum()
a.min()
a.max()
a.mean()
np.median(a)

3.5

In [58]:
np.corrcoef(a)

array([[1., 1.],
       [1., 1.]])

In [60]:
np.std(a)

1.707825127659933

In [61]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [62]:
a1

array([[1, 4, 5],
       [2, 3, 5]])

In [64]:
s=np.sort(a1)
s

array([[1, 4, 5],
       [2, 3, 5]])

In [65]:
s=np.sort(a1,axis=0) # 0 - col, 1-row
s

array([[1, 3, 5],
       [2, 4, 5]])

In [66]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [68]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
a.ravel() 


array([1, 2, 3, 4, 5, 6])

In [70]:
a.reshape(3,-2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
np.append(a,a1)

array([1, 2, 3, 4, 5, 6, 1, 4, 5, 2, 3, 5])

In [72]:
np.insert(a,1,5)

array([1, 5, 2, 3, 4, 5, 6])

In [96]:
np.delete(a,1)

array([1, 3, 4, 5, 6])

In [94]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
a1

array([[1, 4, 5],
       [2, 3, 5]])

In [90]:
np.vstack((a,a1)) #stacks vertically

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 5],
       [2, 3, 5]])

In [91]:
np.hstack((a,a1))  # stacks horizontally(column-wise)

array([[1, 2, 3, 1, 4, 5],
       [4, 5, 6, 2, 3, 5]])

In [92]:
np.r_[a,a1]  #stacks row-wise

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 5],
       [2, 3, 5]])

In [93]:
np.c_[a,a1] #stacks column-wise

array([[1, 2, 3, 1, 4, 5],
       [4, 5, 6, 2, 3, 5]])

In [76]:
np.row_stack((a,a1))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 4, 5],
       [2, 3, 5]])

In [97]:
np.column_stack((a,a1))

array([[1, 2, 3, 1, 4, 5],
       [4, 5, 6, 2, 3, 5]])

In [ ]:
#r_,row_stack,vstack - stack row-wise
#c_,column_stack,hstack - stacks column-wise

In [75]:
np.vsplit(a,2) #split row wise

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [78]:
np.hsplit(a1,3)

[array([[1],
        [2]]),
 array([[4],
        [3]]),
 array([[5],
        [5]])]

In [7]:
g=np.array([1,2,3])
j=np.arange(10,25,5)
j

array([10, 15, 20])

In [8]:
np.concatenate((g,j))

array([ 1,  2,  3, 10, 15, 20])

In [9]:
np.concatenate((g,j),axis=0)

array([ 1,  2,  3, 10, 15, 20])