# Pandas
- Which is a build in Library and using Pandas heavily for data manipulation, visualisation, building machine learning       models, etc.
- There are two main data structures in Pandas - Series and Dataframes
### The pandas Series (similar to a numpy array)
- A dataframe is simply a table where each column is a pandas series.
- Creating a pandas series
- Indexing series
### Dataframes
- Dataframe is the most widely used data-structure in data analysis. It is a table with rows and columns, with rows having   an index and columns having meaningful names.

     - Creating dataframes from dictionaries
     - Importing CSV data files as pandas dataframes
     - Reading and summarising dataframes
     - Sorting dataframes

In [5]:
import pandas

In [6]:
import pandas as pd
#1 2 3 4 5
#0 1 2 3 4
# series index starts from 0
s=pd.Series([1,2,3,4,5,6])
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [8]:
s1 = pd.Series([1,2,"lavanya",4.8989,5,6,7]) # series index starts from 0
print(type(s1))
s1

<class 'pandas.core.series.Series'>


0          1
1          2
2    lavanya
3     4.8989
4          5
5          6
6          7
dtype: object

In [9]:
s1[2:5]
s1[1:6]
s1[1:6:2] 

1         2
3    4.8989
5         6
dtype: object

In [23]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [24]:
s['a':'d']

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d']) #index size should be same 
print(s)

ValueError: Length of passed values is 5, index implies 4.

In [14]:
s[0]

1

In [15]:
s[1]

2

In [16]:
s[1:]

b    2
c    3
d    4
e    5
dtype: int64

In [18]:
s=pd.Series([1,2,3,4,5,6])
s[0:3]

0    1
1    2
2    3
dtype: int64

In [25]:
s[::-1]

e    5
d    4
c    3
b    2
a    1
dtype: int64

In [26]:
s.mean()

3.0

In [27]:
s.median()

3.0

In [28]:
s.mode()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [29]:
s=pd.Series([1,2,3,4,3])
s.mode()

0    3
dtype: int64

# Data Frame


In [30]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [31]:
# creating DF using dict
di = {   "name": ["chandu",'shaik',"keerthi","srikanthi"],
         "age" : [12,34,22,34]
     }
df = pd.DataFrame(di)
df

name  age
0     chandu   12
1      shaik   34
2    keerthi   22
3  srikanthi   34

In [32]:
import numpy as np
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
df=pd.DataFrame(a)
print(df)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [34]:
df=pd.DataFrame({'name':['ravi','raju','geetha'],'m1':[23,34,56],'m2':[34,56,21]})
print(df)

     name  m1  m2
0    ravi  23  34
1    raju  34  56
2  geetha  56  21


In [35]:
df.keys()

Index(['name', 'm1', 'm2'], dtype='object')

In [36]:
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[56, 79, 50, 10],
       [18, 42, 64, 77],
       [34, 79,  5, 23],
       [24, 90, 73, 25],
       [51, 44, 58, 12],
       [56,  5, 12, 35]])

In [37]:
df=pd.DataFrame(a,index=['ravi','raju','geetha','seetha','vikram','fiza'],columns=['m1','m2','m3','p&s'])
print(df)

        m1  m2  m3  p&s
ravi    56  79  50   10
raju    18  42  64   77
geetha  34  79   5   23
seetha  24  90  73   25
vikram  51  44  58   12
fiza    56   5  12   35


In [38]:
df.columns

Index(['m1', 'm2', 'm3', 'p&s'], dtype='object')

In [39]:
df.index

Index(['ravi', 'raju', 'geetha', 'seetha', 'vikram', 'fiza'], dtype='object')

In [40]:
df.columns = ['M1','M2','M3','p&s']
print(df)

        M1  M2  M3  p&s
ravi    56  79  50   10
raju    18  42  64   77
geetha  34  79   5   23
seetha  24  90  73   25
vikram  51  44  58   12
fiza    56   5  12   35


In [41]:
df.index=['Ravi','Raju','Geetha','Seetha','Vikram'] # we have to pass all the indexes in df

ValueError: Length mismatch: Expected axis has 6 elements, new values have 5 elements

In [42]:
df.index=['Ravi','Raju','Geetha','seetha','Vikram','Fiza']

In [43]:
df

M1  M2  M3  p&s
Ravi    56  79  50   10
Raju    18  42  64   77
Geetha  34  79   5   23
seetha  24  90  73   25
Vikram  51  44  58   12
Fiza    56   5  12   35

In [44]:
df.rename(columns={'p&s':'P&S'},index={'seetha':'Seetha'},inplace=True) #if false not change 

In [45]:
df

M1  M2  M3  P&S
Ravi    56  79  50   10
Raju    18  42  64   77
Geetha  34  79   5   23
Seetha  24  90  73   25
Vikram  51  44  58   12
Fiza    56   5  12   35

In [46]:
df.rename(columns={'p&s':'P&S'},index={'seetha':'Seetha'}) #by default it is false so it will not change 
                                                            #we have to mention inplace=True

M1  M2  M3  P&S
Ravi    56  79  50   10
Raju    18  42  64   77
Geetha  34  79   5   23
Seetha  24  90  73   25
Vikram  51  44  58   12
Fiza    56   5  12   35

In [47]:
df['M1'] #only columns can be accessed
         # displayed as series    

Ravi      56
Raju      18
Geetha    34
Seetha    24
Vikram    51
Fiza      56
Name: M1, dtype: int32

In [48]:
df[['M1']] #it is displayed as data frame

M1
Ravi    56
Raju    18
Geetha  34
Seetha  24
Vikram  51
Fiza    56

In [49]:
df['M1'][2]

34

In [50]:
df.loc['Raju'] #using loc we can didplay rows too 

M1     18
M2     42
M3     64
P&S    77
Name: Raju, dtype: int32

In [51]:
df.loc['Raju','M2'] #using loc we can didplay rows too 

42

In [52]:
df.iloc[0]

M1     56
M2     79
M3     50
P&S    10
Name: Ravi, dtype: int32

In [53]:
df.iloc['Raju'] #iloc coinsider only integers

TypeError: Cannot index by location index with a non-integer key

In [54]:
df.iloc[0,0]

56

In [55]:
df.iloc[0:3,0:3]

M1  M2  M3
Ravi    56  79  50
Raju    18  42  64
Geetha  34  79   5

In [56]:
df.iloc[0,0]=45

In [57]:
df

M1  M2  M3  P&S
Ravi    45  79  50   10
Raju    18  42  64   77
Geetha  34  79   5   23
Seetha  24  90  73   25
Vikram  51  44  58   12
Fiza    56   5  12   35

In [58]:
df =pd.DataFrame(np.arange(24).reshape(3,2,4)) #only 2d is acceptable

ValueError: Must pass 2-d input

In [59]:
df

M1  M2  M3  P&S
Ravi    45  79  50   10
Raju    18  42  64   77
Geetha  34  79   5   23
Seetha  24  90  73   25
Vikram  51  44  58   12
Fiza    56   5  12   35

In [60]:
df['M1'].unique() # removes duplicate values

array([45, 18, 34, 24, 51, 56])

In [61]:
len(df['M1'])==len(df['M1'].unique()) #True because no duplicate elements in our table

True

In [62]:
df['M1'].nunique() # number of rows

6

In [101]:
df.iloc[2:4,2:4] = np.NAN

In [102]:
df

M1  M2    M3   P&S
Ravi    45  64   1.0  20.0
Raju     4  88  80.0  52.0
Geetha  37  23   NaN   NaN
Seetha  88   8   NaN   NaN
Vikram  20  79  92.0  39.0
Fiza     6  92  37.0  99.0

In [107]:
df.isna() #in place of NAN values true is replaced we can also use df.isnull() 
          #when there is large data to find nan values we use this method

M1     M2     M3    P&S
Ravi    False  False  False  False
Raju    False  False  False  False
Geetha  False  False   True   True
Seetha  False  False   True   True
Vikram  False  False  False  False
Fiza    False  False  False  False

In [104]:
df.isnull()

M1     M2     M3    P&S
Ravi    False  False  False  False
Raju    False  False  False  False
Geetha  False  False   True   True
Seetha  False  False   True   True
Vikram  False  False  False  False
Fiza    False  False  False  False

In [105]:
df.isnull().sum() #total nan values are displayed

M1     0
M2     0
M3     2
P&S    2
dtype: int64

In [106]:
df.fillna(23) #replace nan values with the given number

M1  M2    M3   P&S
Ravi    45  64   1.0  20.0
Raju     4  88  80.0  52.0
Geetha  37  23  23.0  23.0
Seetha  88   8  23.0  23.0
Vikram  20  79  92.0  39.0
Fiza     6  92  37.0  99.0

In [108]:
df  #but original data is not changed we have to use inplace =True

M1  M2    M3   P&S
Ravi    45  64   1.0  20.0
Raju     4  88  80.0  52.0
Geetha  37  23   NaN   NaN
Seetha  88   8   NaN   NaN
Vikram  20  79  92.0  39.0
Fiza     6  92  37.0  99.0

In [109]:
df.fillna(23,inplace=True)

In [110]:
df

M1  M2    M3   P&S
Ravi    45  64   1.0  20.0
Raju     4  88  80.0  52.0
Geetha  37  23  23.0  23.0
Seetha  88   8  23.0  23.0
Vikram  20  79  92.0  39.0
Fiza     6  92  37.0  99.0

In [63]:
df['M3'].fillna(24,inplace=True)

In [64]:
df

M1  M2  M3  P&S
Ravi    45  79  50   10
Raju    18  42  64   77
Geetha  34  79   5   23
Seetha  24  90  73   25
Vikram  51  44  58   12
Fiza    56   5  12   35

In [120]:
df.

24

In [119]:
df.dtypes

M1       int32
M2       int32
M3     float64
P&S    float64
dtype: object

In [70]:
df=pd.read_excel('Book1.xlsx')
df

s.no    Name  Roll:NO   clg-name course degree
0     1  hafiza       41     dr.LBC    CSE  BTECH
1     2    ghjg       56  tgrg ghfh    CSE  BTECH
2     3    hjgh       77    gfgdfg     CSE  BTECH
3     4  fsdvfv       22    hgfthfh    CSE  BTECH
4     5   meyrg       29      gfhgh    CSE  BTECH

In [79]:
# Reading csv file in dataframe 
data = pd.read_csv("Book2.csv")
data

FileNotFoundError: [Errno 2] File Book2.csv does not exist: 'Book2.csv'